import { Task, Project, User, TaskStatus, TaskPriority } from '../types';

export function generateMockData() {
  const projects: Project[] = [
    {
      id: 'project-1',
      name: 'Marketing Campaign',
      description: 'Q1 Marketing Campaign Planning',
      color: '#4F46E5',
      icon: 'megaphone',
      ownerId: 'user-1',
      members: [
        { userId: 'user-1', role: 'owner', joinedAt: new Date('2024-01-01') },
        { userId: 'user-2', role: 'member', joinedAt: new Date('2024-01-02') },
      ],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-15'),
      isArchived: false,
    },
    {
      id: 'project-2',
      name: 'Product Development',
      description: 'New feature development',
      color: '#059669',
      icon: 'code',
      ownerId: 'user-1',
      members: [
        { userId: 'user-1', role: 'owner', joinedAt: new Date('2024-01-01') },
        { userId: 'user-3', role: 'member', joinedAt: new Date('2024-01-03') },
      ],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-20'),
      isArchived: false,
    },
  ];

  const tasks: Task[] = [
    {
      id: 'task-1',
      title: 'Design Landing Page',
      description: 'Create a modern, responsive landing page for the new campaign',
      status: 'todo',
      priority: 'high',
      dueDate: new Date('2024-02-15'),
      assignedTo: ['user-2'],
      createdBy: 'user-1',
      createdAt: new Date('2024-01-10'),
      updatedAt: new Date('2024-01-10'),
      projectId: 'project-1',
      tags: ['design', 'urgent'],
      subtasks: [
        { id: 'sub-1', title: 'Create wireframes', completed: true, createdAt: new Date() },
        { id: 'sub-2', title: 'Design mockups', completed: false, createdAt: new Date() },
      ],
      comments: [],
      attachments: [],
      estimatedHours: 16,
    },
    {
      id: 'task-2',
      title: 'API Integration',
      description: 'Integrate with third-party payment API',
      status: 'in-progress',
      priority: 'medium',
      dueDate: new Date('2024-02-20'),
      assignedTo: ['user-3'],
      createdBy: 'user-1',
      createdAt: new Date('2024-01-12'),
      updatedAt: new Date('2024-01-18'),
      projectId: 'project-2',
      tags: ['backend', 'api'],
      subtasks: [],
      comments: [
        {
          id: 'comment-1',
          content: 'Started working on the authentication flow',
          author: 'user-3',
          createdAt: new Date('2024-01-18'),
        },
      ],
      attachments: [],
      estimatedHours: 24,
      actualHours: 8,
    },
    {
      id: 'task-3',
      title: 'User Testing',
      description: 'Conduct user testing sessions for the new features',
      status: 'review',
      priority: 'medium',
      dueDate: new Date('2024-02-25'),
      assignedTo: ['user-2'],
      createdBy: 'user-1',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-22'),
      projectId: 'project-1',
      tags: ['testing', 'ux'],
      subtasks: [],
      comments: [],
      attachments: [],
      estimatedHours: 12,
      actualHours: 10,
    },
    {
      id: 'task-4',
      title: 'Documentation Update',
      description: 'Update API documentation with new endpoints',
      status: 'completed',
      priority: 'low',
      dueDate: new Date('2024-02-10'),
      assignedTo: ['user-3'],
      createdBy: 'user-1',
      createdAt: new Date('2024-01-08'),
      updatedAt: new Date('2024-01-25'),
      completedAt: new Date('2024-01-25'),
      projectId: 'project-2',
      tags: ['documentation'],
      subtasks: [],
      comments: [],
      attachments: [],
      estimatedHours: 6,
      actualHours: 5,
    },
    {
      id: 'task-5',
      title: 'Mobile App Prototype',
      description: 'Create interactive prototype for mobile application',
      status: 'todo',
      priority: 'urgent',
      dueDate: new Date('2024-02-12'),
      assignedTo: ['user-2'],
      createdBy: 'user-1',
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-01-20'),
      projectId: 'project-2',
      tags: ['mobile', 'prototype', 'design'],
      subtasks: [],
      comments: [],
      attachments: [],
      estimatedHours: 20,
    },
  ];
  const subscriptionPlans = [
  {
    id: 'free',
    title: 'Free Plan – Get Started',
    description: 'Perfect for individuals or small teams just getting started. Create tasks, organize your to-dos, and stay focused — all for free.',
    features: [
      'Up to 3 projects',
      'Basic task management',
      'Personal dashboard',
    ],
    price: 0,
  },
  {
    id: 'pro',
    title: 'Pro Plan – Boost Productivity',
    description: 'For growing teams and power users. Unlock collaboration tools, deadlines, recurring tasks, and enhanced reminders to manage work efficiently.',
    features: [
      'Unlimited projects',
      'Team collaboration',
      'Deadline & reminder features',
      'File attachments',
    ],
    price: 29,
  },
  {
    id: 'team',
    title: 'Team Plan – Collaborate at Scale',
    description: 'Built for teams and organizations. Get priority support, advanced permissions, and full access to productivity and reporting tools.',
    features: [
      'All Pro features',
      'Team roles & permissions',
      'Activity logs',
      'Priority support',
      'Advanced reporting',
    ],
    price: 59,
  },
]


  return { tasks, projects, subscriptionPlans };
}